### PR TITLE
README: add caveat part to clarify the boundary of go-etcd

### PR DESCRIPTION
**Pull request by yichengq**
helps https://github.com/coreos/etcd/issues/2677
helps https://github.com/GoogleCloudPlatform/kubernetes/issues/7566

feedback is welcomed.

/cc @xiang90

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM.

/cc @barakmich @robszumski

**Comment by robszumski** [comment]
Seems ok to me!

**Comment by xiang90** [comment]
@timothysc Is this OK to you?

**Comment by timothysc** [comment]
LGTM.  examples would be good too ;-)

**Comment by xiang90** [comment]
@timothysc Will do too. Thanks.

**Pull request merged**
