### PR TITLE
Regenerate response code with codecgen v3

### PR DESCRIPTION
**Pull request by TauZero**
`codec` recently upgraded to GenVersion 3, which requires code to be regenerated
https://github.com/ugorji/go/commit/718a1bcd1902bb42e926b0e54f6686879f5a9a79

Regenerated the response code with `go generate response.go`. Tests pass on my machine.

### CODE REVIEW

**Comment by SpComb** [comment]
Confirmed to fix #240

	$ git -C src/github.com/coreos/go-etcd/ pull https://github.com/TauZero/go-etcd.git codecgen_v2_to_v3
	remote: Counting objects: 4, done.
	remote: Compressing objects: 100% (4/4), done.
	remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
	Unpacking objects: 100% (4/4), done.
	From https://github.com/TauZero/go-etcd
	 * branch            codecgen_v2_to_v3 -> FETCH_HEAD
	Updating 6a4f8f4..bebe7ef
	Fast-forward
	 etcd/response.generated.go | 1731 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------
	 1 file changed, 1013 insertions(+), 718 deletions(-)
	$ rm -rf pkg/
	$ etcdctl get /foo
	Error:  100: Key not found (/foo) [18946547]
	$ go run etcd-example.go 
	$ etcdctl get /foo
	bar

**Comment by jonboulle** [comment]
thanks!

**Comment by dsociative** [comment]
Hi, today I got a red builds in jenkins with go-etcd from master branch [error log here](https://gist.github.com/dsociative/731ddaf85cb944526f68)
Change version to v2.0.0 and the error was gone

**Comment by msneeden** [comment]
Seeing the same...
```
+ go get
# github.com/coreos/go-etcd/etcd
../../../github.com/coreos/go-etcd/etcd/response.generated.go:112: r.EncodeMapKVSeparator undefined (type codec.encDriver has no field or method EncodeMapKVSeparator)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:123: r.EncodeArrayEntrySeparator undefined (type codec.encDriver has no field or method EncodeArrayEntrySeparator)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:137: r.EncodeMapEntrySeparator undefined (type codec.encDriver has no field or method EncodeMapEntrySeparator)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:143: r.EncodeMapKVSeparator undefined (type codec.encDriver has no field or method EncodeMapKVSeparator)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:158: r.EncodeArrayEntrySeparator undefined (type codec.encDriver has no field or method EncodeArrayEntrySeparator)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:173: r.EncodeMapEntrySeparator undefined (type codec.encDriver has no field or method EncodeMapEntrySeparator)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:179: r.EncodeMapKVSeparator undefined (type codec.encDriver has no field or method EncodeMapKVSeparator)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:195: r.EncodeArrayEnd undefined (type codec.encDriver has no field or method EncodeArrayEnd)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:197: r.EncodeMapEnd undefined (type codec.encDriver has no field or method EncodeMapEnd)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:216: r.ReadMapEnd undefined (type codec.decDriver has no field or method ReadMapEnd)
../../../github.com/coreos/go-etcd/etcd/response.generated.go:216: too many errors
```

**Comment by TauZero** [comment]
What version of `github.com/ugorji/go/codec` do you have installed?

**Comment by zstyblik** [comment]
> What version of github.com/ugorji/go/codec do you have installed?

Following gopath, I'd say https://github.com/ugorji/go/commit/1d5269ed4e89d423d40362a0914e1c99adb13cc8

**Comment by TauZero** [comment]
This fix was when https://github.com/ugorji/go/commit/718a1bcd1902bb42e926b0e54f6686879f5a9a79 was the latest (GenVersion3) (2 days ago).

Looks like they updated again today https://github.com/ugorji/go/commit/1d5269ed4e89d423d40362a0914e1c99adb13cc8 which brings some major changes and a bump to GenVersion4.

Gotta love golang dependency management...

**Comment by zstyblik** [comment]
@TauZero just to note, I'm not related to any previous participants.

**Pull request merged**
