### PR TITLE
request: follow http redirection

### PR DESCRIPTION
**Pull request by xiang90**
Follow http redirection. HTTP redirection happens when
go-etcd operates on old etcd cluster or on a "proxy".

Note: If go-etcd works with old 0.4.6 cluster, this will decrease the performance since it does not track the leader.

### CODE REVIEW

**Comment by yichengq** [comment]
lgtm

**Comment by philips** [comment]
lgtm as it re-adds the code from here: https://github.com/coreos/go-etcd/commit/5348c80bde6223fa53c48ef546b4802db69b1d70#diff-d8e09433868650c0b3b3b69230f45466L298

But it seems like we would need to address [this](https://github.com/coreos/go-etcd/commit/5348c80bde6223fa53c48ef546b4802db69b1d70#commitcomment-9524287) in order to get this client to actually support etcd v2+ and etcd 0.4.

**Comment by xiang90** [comment]
@philips Sure. This is another problem I am addressing. But it will be in another pull request.

**Comment by bakins** [comment]
LGTM

**Pull request merged**
