### PR TITLE
Use ugorji codec for unmarshalling responses from etcd server.

### LINKED ISSUE #217: Improve performance of reading responses from etcd by using ugorji codec
In kubernetes we intensively use etcd go client library to communicate with etcd server. We've noticed that unmarshalling responses from etcd takes significant amount of time. One option to improve performance of this library would be to use [ugorji code](https://github.com/ugorji/go/tree/master/codec) that generates code for (un)marshalling, which is much faster than a regular go codec that uses reflections.

I did initial benchmarks and it gives around ~2 speed up (depending on the size of a Node).

Would this change be considered if I sent it. It should be very short (1 file with generated code, one line change in response.go and some benchmarks).

@davidopp @wojtek-t

### PR DESCRIPTION
**Pull request by fgrzadkowski**
This change speeds up RawResponse.Unmarshal ~2x:

BEFORE:
```
$ go test -test.run=XXXXX -bench=.*
PASS
BenchmarkSmallResponseUnmarshal		   10000	    180181 ns/op
BenchmarkManySmallResponseUnmarshal	     100	  15115904 ns/op
BenchmarkMediumResponseUnmarshal	    1000	   2302976 ns/op
BenchmarkLargeResponseUnmarshal		      20	  94022971 ns/op
ok  	github.com/coreos/go-etcd/etcd	8.963s
```

AFTER:
```
$ go test -test.run=XXXXX -bench=.*
PASS
BenchmarkSmallResponseUnmarshal		   20000	     85873 ns/op
BenchmarkManySmallResponseUnmarshal	     200	   7069753 ns/op
BenchmarkMediumResponseUnmarshal	    1000	   1339490 ns/op
BenchmarkLargeResponseUnmarshal		      20	  60579560 ns/op
ok  	github.com/coreos/go-etcd/etcd	7.604s
```

I also updated install section in README.md file to make it clear that user have to ```go get``` ugorji codec.

Fixes #217 
Refs https://github.com/GoogleCloudPlatform/kubernetes/issues/4521

@davidopp @wojtek-t @xiang90 @timothysc

### CODE REVIEW

**Comment by xiang90** [comment]
@fgrzadkowski I am OK with this change. I am not sure how will this improve the overall perf of k8s.

A more interesting question is: do you also want to do this at server side? Why not let etcd server accept protobuf if you really care about perf?

**Comment by fgrzadkowski** [comment]
I think that moving towards protobuf makes sense, but it seems like a major change. This one is simple and from manual tests it improves latency metrics by 20-30%.

**Comment by timothysc** [comment]
@xiang90 crossref - https://github.com/GoogleCloudPlatform/kubernetes/issues/8132

**Comment by philips** [comment]
This is great. We should also do it for the still developing `github.com/coreos/etcd/client` package. Also, we should not vendor the codec package as go-etcd is a library.

Overall, LGTM.

**Comment by xiang90** [comment]
LGTM

/cc @yichengq you are more familiar with go-etcd codebase.

**Comment by yichengq** [comment]
lgtm

**Pull request merged**
